mkdir npyG1B_
mkdir npyG1E_
mkdir npyG1F_
mkdir npyR1B_
mkdir npyR1E_
mkdir npyR1F_
mkdir npyN1B_
mkdir npyN1E_
mkdir npyN1F_
mkdir npyG2B_
mkdir npyG2E_
mkdir npyG2F_
mkdir npyR2B_
mkdir npyR2E_
mkdir npyR2F_
mkdir npyN2B_
mkdir npyN2E_
mkdir npyN2F_

mkdir npyG1B_LK_
mkdir npyG1E_LK_
mkdir npyG1F_LK_
mkdir npyR1B_LK_
mkdir npyR1E_LK_
mkdir npyR1F_LK_
mkdir npyN1B_LK_
mkdir npyN1E_LK_
mkdir npyN1F_LK_
mkdir npyG2B_LK_
mkdir npyG2E_LK_
mkdir npyG2F_LK_
mkdir npyR2B_LK_
mkdir npyR2E_LK_
mkdir npyR2F_LK_
mkdir npyN2B_LK_
mkdir npyN2E_LK_
mkdir npyN2F_LK_

mkdir npyG1B_LB_
mkdir npyG1E_LB_
mkdir npyG1F_LB_
mkdir npyR1B_LB_
mkdir npyR1E_LB_
mkdir npyR1F_LB_
mkdir npyN1B_LB_
mkdir npyN1E_LB_
mkdir npyN1F_LB_
mkdir npyG2B_LB_
mkdir npyG2E_LB_
mkdir npyG2F_LB_
mkdir npyR2B_LB_
mkdir npyR2E_LB_
mkdir npyR2F_LB_
mkdir npyN2B_LB_
mkdir npyN2E_LB_
mkdir npyN2F_LB_

for i in {1..13}
do
sbatch l_run_experiment_1_g_b_$i.sh
sleep 1
sbatch l_run_experiment_1_g_e_$i.sh
sleep 1
sbatch l_run_experiment_1_g_f_$i.sh
sleep 1
sbatch l_run_experiment_1_r_b_$i.sh
sleep 1
sbatch l_run_experiment_1_r_e_$i.sh
sleep 1
sbatch l_run_experiment_1_r_f_$i.sh
sleep 1
sbatch l_run_experiment_1_n_b_$i.sh
sleep 1
sbatch l_run_experiment_1_n_e_$i.sh
sleep 1
sbatch l_run_experiment_1_n_f_$i.sh
sleep 1
sbatch l_run_experiment_2_g_b_$i.sh
sleep 1
sbatch l_run_experiment_2_g_e_$i.sh
sleep 1
sbatch l_run_experiment_2_g_f_$i.sh
sleep 1
sbatch l_run_experiment_2_r_b_$i.sh
sleep 1
sbatch l_run_experiment_2_r_e_$i.sh
sleep 1
sbatch l_run_experiment_2_r_f_$i.sh
sleep 1
sbatch l_run_experiment_2_n_b_$i.sh
sleep 1
sbatch l_run_experiment_2_n_e_$i.sh
sleep 1
sbatch l_run_experiment_2_n_f_$i.sh
sleep 1

sbatch l_run_experiment_1_g_b_LK_$i.sh
sleep 1
sbatch l_run_experiment_1_g_e_LK_$i.sh
sleep 1
sbatch l_run_experiment_1_g_f_LK_$i.sh
sleep 1
sbatch l_run_experiment_1_r_b_LK_$i.sh
sleep 1
sbatch l_run_experiment_1_r_e_LK_$i.sh
sleep 1
sbatch l_run_experiment_1_r_f_LK_$i.sh
sleep 1
sbatch l_run_experiment_1_n_b_LK_$i.sh
sleep 1
sbatch l_run_experiment_1_n_e_LK_$i.sh
sleep 1
sbatch l_run_experiment_1_n_f_LK_$i.sh
sleep 1
sbatch l_run_experiment_2_g_b_LK_$i.sh
sleep 1
sbatch l_run_experiment_2_g_e_LK_$i.sh
sleep 1
sbatch l_run_experiment_2_g_f_LK_$i.sh
sleep 1
sbatch l_run_experiment_2_r_b_LK_$i.sh
sleep 1
sbatch l_run_experiment_2_r_e_LK_$i.sh
sleep 1
sbatch l_run_experiment_2_r_f_LK_$i.sh
sleep 1
sbatch l_run_experiment_2_n_b_LK_$i.sh
sleep 1
sbatch l_run_experiment_2_n_e_LK_$i.sh
sleep 1
sbatch l_run_experiment_2_n_f_LK_$i.sh
sleep 1

sbatch l_run_experiment_1_g_b_LB_$i.sh
sleep 1
sbatch l_run_experiment_1_g_e_LB_$i.sh
sleep 1
sbatch l_run_experiment_1_g_f_LB_$i.sh
sleep 1
sbatch l_run_experiment_1_r_b_LB_$i.sh
sleep 1
sbatch l_run_experiment_1_r_e_LB_$i.sh
sleep 1
sbatch l_run_experiment_1_r_f_LB_$i.sh
sleep 1
sbatch l_run_experiment_1_n_b_LB_$i.sh
sleep 1
sbatch l_run_experiment_1_n_e_LB_$i.sh
sleep 1
sbatch l_run_experiment_1_n_f_LB_$i.sh
sleep 1
sbatch l_run_experiment_2_g_b_LB_$i.sh
sleep 1
sbatch l_run_experiment_2_g_e_LB_$i.sh
sleep 1
sbatch l_run_experiment_2_g_f_LB_$i.sh
sleep 1
sbatch l_run_experiment_2_r_b_LB_$i.sh
sleep 1
sbatch l_run_experiment_2_r_e_LB_$i.sh
sleep 1
sbatch l_run_experiment_2_r_f_LB_$i.sh
sleep 1
sbatch l_run_experiment_2_n_b_LB_$i.sh
sleep 1
sbatch l_run_experiment_2_n_e_LB_$i.sh
sleep 1
sbatch l_run_experiment_2_n_f_LB_$i.sh
sleep 1
done
