library(cidr)

raw_counts<-read.table(file='/storage/hpc/scratch/yjiang/SCwangjuexin/scGNN-master_021720/scGNN-master/otherresults/recon/recon_data2/9.Chung_LTMG_0.1_0.0-0.3-0.1_recon.csv',sep=",",header=FALSE)
raw_counts=exp(raw_counts)
tags=t(raw_counts)
colnames(tags)=rownames(raw_counts)
sData <- scDataConstructor(tags)
sData <- determineDropoutCandidates(sData)
sData <- wThreshold(sData)
sData <- scDissim(sData)
sData <- scPCA(sData)
sData <- nPC(sData)
nCluster(sData)
sData <- scCluster(sData)
write.table(sData@clusters, file = "/storage/hpc/scratch/yjiang/SCwangjuexin/scGNN-master_021720/scGNN-master/otherresults/recon/round_2exp/CIDR/9.Chung_clusters.csv", quote = F,row.names=FALSE,col.names=FALSE,sep=",")
write.table(sData@PC, file = "/storage/hpc/scratch/yjiang/SCwangjuexin/scGNN-master_021720/scGNN-master/otherresults/recon/round_2exp/CIDR/9.Chung_z.csv", quote = F,row.names=FALSE,col.names=FALSE,sep=",")


raw_counts<-read.table(file='/storage/hpc/scratch/yjiang/SCwangjuexin/scGNN-master_021720/scGNN-master/otherresults/recon/recon_data2/11.Kolodziejczyk_LTMG_0.1_0.0-0.3-0.1_recon.csv',sep=",",header=FALSE)
raw_counts=exp(raw_counts)
tags=t(raw_counts)
colnames(tags)=rownames(raw_counts)
sData <- scDataConstructor(tags)
sData <- determineDropoutCandidates(sData)
sData <- wThreshold(sData)
sData <- scDissim(sData)
sData <- scPCA(sData)
sData <- nPC(sData)
nCluster(sData)
sData <- scCluster(sData)
write.table(sData@clusters, file = "/storage/hpc/scratch/yjiang/SCwangjuexin/scGNN-master_021720/scGNN-master/otherresults/recon/round_2exp/CIDR/11.Kolodziejczyk_clusters.csv", quote = F,row.names=FALSE,col.names=FALSE,sep=",")
write.table(sData@PC, file = "/storage/hpc/scratch/yjiang/SCwangjuexin/scGNN-master_021720/scGNN-master/otherresults/recon/round_2exp/CIDR/11.Kolodziejczyk_z.csv", quote = F,row.names=FALSE,col.names=FALSE,sep=",")


raw_counts<-read.table(file='/storage/hpc/scratch/yjiang/SCwangjuexin/scGNN-master_021720/scGNN-master/otherresults/recon/recon_data2/12.Klein_LTMG_0.1_0.0-0.3-0.1_recon.csv',sep=",",header=FALSE)
raw_counts=exp(raw_counts)
tags=t(raw_counts)
colnames(tags)=rownames(raw_counts)
sData <- scDataConstructor(tags)
sData <- determineDropoutCandidates(sData)
sData <- wThreshold(sData)
sData <- scDissim(sData)
sData <- scPCA(sData)
sData <- nPC(sData)
nCluster(sData)
sData <- scCluster(sData)
write.table(sData@clusters, file = "/storage/hpc/scratch/yjiang/SCwangjuexin/scGNN-master_021720/scGNN-master/otherresults/recon/round_2exp/CIDR/12.Klein_clusters.csv", quote = F,row.names=FALSE,col.names=FALSE,sep=",")
write.table(sData@PC, file = "/storage/hpc/scratch/yjiang/SCwangjuexin/scGNN-master_021720/scGNN-master/otherresults/recon/round_2exp/CIDR/12.Klein_z.csv", quote = F,row.names=FALSE,col.names=FALSE,sep=",")


raw_counts<-read.table(file='/storage/hpc/scratch/yjiang/SCwangjuexin/scGNN-master_021720/scGNN-master/otherresults/recon/recon_data2/13.Zeisel_LTMG_0.1_0.0-0.3-0.1_recon.csv',sep=",",header=FALSE)
raw_counts=exp(raw_counts)
tags=t(raw_counts)
colnames(tags)=rownames(raw_counts)
sData <- scDataConstructor(tags)
sData <- determineDropoutCandidates(sData)
sData <- wThreshold(sData)
sData <- scDissim(sData)
sData <- scPCA(sData)
sData <- nPC(sData)
nCluster(sData)
sData <- scCluster(sData)
write.table(sData@clusters, file = "/storage/hpc/scratch/yjiang/SCwangjuexin/scGNN-master_021720/scGNN-master/otherresults/recon/round_2exp/CIDR/13.Zeisel_clusters.csv", quote = F,row.names=FALSE,col.names=FALSE,sep=",")
write.table(sData@PC, file = "/storage/hpc/scratch/yjiang/SCwangjuexin/scGNN-master_021720/scGNN-master/otherresults/recon/round_2exp/CIDR/13.Zeisel_z.csv", quote = F,row.names=FALSE,col.names=FALSE,sep=",")
