library(RaceID)

raw_counts<-read.table(file='/storage/hpc/scratch/yjiang/SCwangjuexin/scGNN-master_021720/scGNN-master/otherresults/recon/recon_data2/9.Chung_LTMG_0.1_0.0-0.3-0.1_recon.csv',sep=",",header=FALSE)
raw_counts=exp(raw_counts)
tags=t(raw_counts)
colnames(tags)=rownames(raw_counts)
sc <- SCseq(tags)
sc <- filterdata(sc,mintotal=1)
fdata <- getfdata(sc)
sc <- compdist(sc,metric="pearson")
sc <- clustexp(sc)
write.table(sc@cluster$kpart, file = "/storage/hpc/scratch/yjiang/SCwangjuexin/scGNN-master_021720/scGNN-master/otherresults/recon/round_2exp/raceID/9.Chung_clusters.csv", quote = F,row.names=FALSE,col.names=FALSE,sep=",")

raw_counts<-read.table(file='/storage/hpc/scratch/yjiang/SCwangjuexin/scGNN-master_021720/scGNN-master/otherresults/recon/recon_data2/11.Kolodziejczyk_LTMG_0.1_0.0-0.3-0.1_recon.csv',sep=",",header=FALSE)
#raw_counts=raw_counts[, colSums(raw_counts != 0) > 0]
raw_counts=exp(raw_counts)
tags=t(raw_counts)
colnames(tags)=rownames(raw_counts)
sc <- SCseq(tags)
sc <- filterdata(sc,mintotal=1)
fdata <- getfdata(sc)
sc <- compdist(sc,metric="pearson")
sc <- clustexp(sc)
write.table(sc@cluster$kpart, file = "/storage/hpc/scratch/yjiang/SCwangjuexin/scGNN-master_021720/scGNN-master/otherresults/recon/round_2exp/raceID/11.Kolodziejczyk_clusters.csv", quote = F,row.names=FALSE,col.names=FALSE,sep=",")

raw_counts<-read.table(file='/storage/hpc/scratch/yjiang/SCwangjuexin/scGNN-master_021720/scGNN-master/otherresults/recon/recon_data2/12.Klein_LTMG_0.1_0.0-0.3-0.1_recon.csv',sep=",",header=FALSE)
raw_counts=exp(raw_counts)
tags=t(raw_counts)
colnames(tags)=rownames(raw_counts)
sc <- SCseq(tags)
sc <- filterdata(sc,mintotal=1)
fdata <- getfdata(sc)
sc <- compdist(sc,metric="pearson")
sc <- clustexp(sc)
write.table(sc@cluster$kpart, file = "/storage/hpc/scratch/yjiang/SCwangjuexin/scGNN-master_021720/scGNN-master/otherresults/recon/round_2exp/raceID/12.Klein_clusters.csv", quote = F,row.names=FALSE,col.names=FALSE,sep=",")

raw_counts<-read.table(file='/storage/hpc/scratch/yjiang/SCwangjuexin/scGNN-master_021720/scGNN-master/otherresults/recon/recon_data2/13.Zeisel_LTMG_0.1_0.0-0.3-0.1_recon.csv',sep=",",header=FALSE)
raw_counts=exp(raw_counts)
tags=t(raw_counts)
colnames(tags)=rownames(raw_counts)
sc <- SCseq(tags)
sc <- filterdata(sc,mintotal=1)
fdata <- getfdata(sc)
sc <- compdist(sc,metric="pearson")
sc <- clustexp(sc)
write.table(sc@cluster$kpart, file = "/storage/hpc/scratch/yjiang/SCwangjuexin/scGNN-master_021720/scGNN-master/otherresults/recon/round_2exp/raceID/13.Zeisel_clusters.csv", quote = F,row.names=FALSE,col.names=FALSE,sep=",")
