library(Seurat)

raw_counts<-read.table(file='/storage/hpc/scratch/yjiang/SCwangjuexin/scGNN-master_021720/scGNN-master/otherresults/recon/recon_data2/9.Chung_LTMG_0.1_0.0-0.3-0.1_recon.csv',sep=",",header=FALSE)
raw_counts=exp(raw_counts)
data=t(raw_counts)
colnames(data)=rownames(raw_counts)
mydata <- CreateSeuratObject(data, project = "mydata_scRNAseq")
mydata <- FindVariableFeatures(mydata)
mydata <- ScaleData(mydata, verbose = FALSE)
mydata <- RunPCA(mydata, npcs = 15)
mydata <- FindNeighbors(mydata, reduction = "pca", dims = 1:15)
mydata <- FindClusters(mydata,resolution = 1)
write.table(Idents(mydata), file = "/storage/hpc/scratch/yjiang/SCwangjuexin/scGNN-master_021720/scGNN-master/otherresults/recon/round_2exp/seurat/9.Chung_clusters.csv", quote = F,row.names=FALSE,col.names=FALSE,sep=",")
write.table(mydata@reductions$pca@cell.embeddings, file = "/storage/hpc/scratch/yjiang/SCwangjuexin/scGNN-master_021720/scGNN-master/otherresults/recon/round_2exp/seurat/9.Chung_z.csv", quote = F,row.names=FALSE,col.names=FALSE,sep=",")


raw_counts<-read.table(file='/storage/hpc/scratch/yjiang/SCwangjuexin/scGNN-master_021720/scGNN-master/otherresults/recon/recon_data2/11.Kolodziejczyk_LTMG_0.1_0.0-0.3-0.1_recon.csv',sep=",",header=FALSE)
raw_counts=exp(raw_counts)
data=t(raw_counts)
colnames(data)=rownames(raw_counts)
mydata <- CreateSeuratObject(data, project = "mydata_scRNAseq")
mydata <- FindVariableFeatures(mydata)
mydata <- ScaleData(mydata, verbose = FALSE)
mydata <- RunPCA(mydata, npcs = 15)
mydata <- FindNeighbors(mydata, reduction = "pca", dims = 1:15)
mydata <- FindClusters(mydata,resolution = 1)
write.table(Idents(mydata), file = "/storage/hpc/scratch/yjiang/SCwangjuexin/scGNN-master_021720/scGNN-master/otherresults/recon/round_2exp/seurat/11.Kolodziejczyk_clusters.csv", quote = F,row.names=FALSE,col.names=FALSE,sep=",")
write.table(mydata@reductions$pca@cell.embeddings, file = "/storage/hpc/scratch/yjiang/SCwangjuexin/scGNN-master_021720/scGNN-master/otherresults/recon/round_2exp/seurat/11.Kolodziejczyk_z.csv", quote = F,row.names=FALSE,col.names=FALSE,sep=",")


raw_counts<-read.table(file='/storage/hpc/scratch/yjiang/SCwangjuexin/scGNN-master_021720/scGNN-master/otherresults/recon/recon_data2/12.Klein_LTMG_0.1_0.0-0.3-0.1_recon.csv',sep=",",header=FALSE)
raw_counts=exp(raw_counts)
data=t(raw_counts)
colnames(data)=rownames(raw_counts)
mydata <- CreateSeuratObject(data, project = "mydata_scRNAseq")
mydata <- FindVariableFeatures(mydata)
mydata <- ScaleData(mydata, verbose = FALSE)
mydata <- RunPCA(mydata, npcs = 15)
mydata <- FindNeighbors(mydata, reduction = "pca", dims = 1:15)
mydata <- FindClusters(mydata,resolution = 1)
write.table(Idents(mydata), file = "/storage/hpc/scratch/yjiang/SCwangjuexin/scGNN-master_021720/scGNN-master/otherresults/recon/round_2exp/seurat/12.Klein_clusters.csv", quote = F,row.names=FALSE,col.names=FALSE,sep=",")
write.table(mydata@reductions$pca@cell.embeddings, file = "/storage/hpc/scratch/yjiang/SCwangjuexin/scGNN-master_021720/scGNN-master/otherresults/recon/round_2exp/seurat/12.Klein_z.csv", quote = F,row.names=FALSE,col.names=FALSE,sep=",")


raw_counts<-read.table(file='/storage/hpc/scratch/yjiang/SCwangjuexin/scGNN-master_021720/scGNN-master/otherresults/recon/recon_data2/13.Zeisel_LTMG_0.1_0.0-0.3-0.1_recon.csv',sep=",",header=FALSE)
raw_counts=exp(raw_counts)
data=t(raw_counts)
colnames(data)=rownames(raw_counts)
mydata <- CreateSeuratObject(data, project = "mydata_scRNAseq")
mydata <- FindVariableFeatures(mydata)
mydata <- ScaleData(mydata, verbose = FALSE)
mydata <- RunPCA(mydata, npcs = 15)
mydata <- FindNeighbors(mydata, reduction = "pca", dims = 1:15)
mydata <- FindClusters(mydata,resolution = 1)
write.table(Idents(mydata), file = "/storage/hpc/scratch/yjiang/SCwangjuexin/scGNN-master_021720/scGNN-master/otherresults/recon/round_2exp/seurat/13.Zeisel_clusters.csv", quote = F,row.names=FALSE,col.names=FALSE,sep=",")
write.table(mydata@reductions$pca@cell.embeddings, file = "/storage/hpc/scratch/yjiang/SCwangjuexin/scGNN-master_021720/scGNN-master/otherresults/recon/round_2exp/seurat/13.Zeisel_z.csv", quote = F,row.names=FALSE,col.names=FALSE,sep=",")

